name: Build VSIX
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Upgrading to v20 fixes 
          
      - run: npm install
      
      - name: Package Extension
        # Using the official modern package name
        run: npx @vscode/vsce package --no-dependencies
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fscss-extension
          path: "*.vsix"

